name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build, then Test any available iPhone simulator
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      #      - run: sudo xcode-select -switch /Applications/Xcode_16.2.app
      - run: |
          xcodebuild test \
          -scheme SureUniversalAssignment \
          -destination "platform=iOS Simulator,OS=18.3.1,name=iPhone 16 Pro" | xcbeautify 

